### Import libraries

In [1]:
import os
import pandas as pd
import copy

### List of directories with corresponding paths:

In [2]:
main_dir = os.path.abspath('..') # os.path.join(os.getcwd())
data_dir = os.path.join(main_dir, "Data")
shapefiles_dir = os.path.join(main_dir, data_dir, "shapefiles")

# Loading Crime Only dataset (original from DC Crime Data)

In [3]:
df_pre_covid_crime_only = pd.read_csv(os.path.join(data_dir, "Merged", "crime_pre-covid_time_data.csv"))
df_covid_crime_only = pd.read_csv(os.path.join(data_dir, "Merged", "crime_covid_time_data.csv"))

df_pre_covid_crime_only['START_DATE'] = pd.to_datetime(df_pre_covid_crime_only['START_DATE'])
df_covid_crime_only['START_DATE'] = pd.to_datetime(df_covid_crime_only['START_DATE'])

df_pre_covid_crime_only = df_pre_covid_crime_only.set_index(df_pre_covid_crime_only['START_DATE'])
df_covid_crime_only = df_covid_crime_only.set_index(df_covid_crime_only['START_DATE'])

del df_pre_covid_crime_only["START_DATE.1"]
del df_covid_crime_only["START_DATE.1"]

df_pre_covid_crime_only['date'] = pd.to_datetime(df_pre_covid_crime_only['START_DATE'].dt.date)
df_covid_crime_only['date'] = pd.to_datetime(df_covid_crime_only['START_DATE'].dt.date)


print("df_pre_covid_crime_only.shape:", df_pre_covid_crime_only.shape)
print("df_covid_crime_only.shape:", df_covid_crime_only.shape)

df_pre_covid_crime_only.shape: (106617, 14)
df_covid_crime_only.shape: (44163, 14)

In [4]:
df_pre_covid_crime_only

,START_DATE,REPORT_DAT,SHIFT,METHOD,OFFENSE,BLOCK,XBLOCK,YBLOCK,WARD,DISTRICT,LATITUDE,LONGITUDE,END_DATE,date
START_DATE,,,,,,,,,,,,,,
2017-01-01 00:28:57+00:00,2017-01-01 00:28:57+00:00,2017-01-02 01:16:13+00:00,EVENING,OTHERS,THEFT/OTHER,1900 - 2199 BLOCK OF RIDGECREST COURT SE,402201.041504,131112.794647,8.0,7.0,38.847816,-76.974645,2017-01-01 00:45:35+00:00,2017-01-01
2017-01-01 01:00:51+00:00,2017-01-01 01:00:51+00:00,2017-01-02 17:20:02+00:00,DAY,OTHERS,THEFT F/AUTO,1700 - 1799 BLOCK OF P STREET NW,396523.770000,137976.790000,2.0,2.0,38.909645,-77.040080,2017-01-02 03:00:58+00:00,2017-01-01
2017-01-01 01:00:56+00:00,2017-01-01 01:00:56+00:00,2017-01-02 02:51:06+00:00,EVENING,OTHERS,THEFT F/AUTO,1821 - 1899 BLOCK OF 16TH STREET NW,396834.070000,138593.520000,2.0,3.0,38.915202,-77.036505,2017-01-01 20:30:39+00:00,2017-01-01
2017-01-01 01:30:04+00:00,2017-01-01 01:30:04+00:00,2017-01-01 17:33:08+00:00,DAY,OTHERS,THEFT F/AUTO,1400 - 1499 BLOCK OF HALF STREET SW,399075.686781,133852.279706,6.0,1.0,38.872497,-77.010652,2017-01-01 16:30:44+00:00,2017-01-01
2017-01-01 02:00:06+00:00,2017-01-01 02:00:06+00:00,2017-01-01 18:01:13+00:00,DAY,OTHERS,THEFT F/AUTO,1700 - 1799 BLOCK OF HOLBROOK STREET NE,401675.560000,137731.620000,5.0,5.0,38.907442,-76.980682,NaN,2017-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-03-06 23:00:21+00:00,2020-03-06 23:00:21+00:00,2020-03-08 14:38:06+00:00,DAY,OTHERS,THEFT F/AUTO,2300 - 2499 BLOCK OF 11TH STREET NW,397655.460000,139302.910000,1.0,3.0,38.921595,-77.027036,2020-03-08 13:00:23+00:00,2020-03-06
2020-03-06 23:00:22+00:00,2020-03-06 23:00:22+00:00,2020-03-09 18:51:35+00:00,DAY,OTHERS,THEFT F/AUTO,4000 - 4099 BLOCK OF CONNECTICUT AVENUE NW,394628.610000,141513.270000,3.0,2.0,38.941494,-77.061958,2020-03-09 12:30:14+00:00,2020-03-06
2020-03-06 23:05:06+00:00,2020-03-06 23:05:06+00:00,2020-03-06 23:37:04+00:00,EVENING,OTHERS,THEFT/OTHER,1100 - 1199 BLOCK OF 10TH STREET NW,397746.000000,137450.410000,2.0,3.0,38.904908,-77.025986,2020-03-06 23:10:21+00:00,2020-03-06
2020-03-06 23:09:14+00:00,2020-03-06 23:09:14+00:00,2020-03-07 00:55:52+00:00,EVENING,OTHERS,THEFT/OTHER,600 - 699 BLOCK OF K STREET NW,398186.040000,137185.330000,6.0,1.0,38.902521,-77.020912,2020-03-06 23:40:10+00:00,2020-03-06
2020-03-06 23:13:43+00:00,2020-03-06 23:13:43+00:00,2020-03-07 03:13:10+00:00,EVENING,GUN,ASSAULT W/DANGEROUS WEAPON,6200 - 6299 BLOCK OF DIX STREET NE,407656.273317,136279.011580,7.0,6.0,38.894325,-76.911744,2020-03-07 03:08:27+00:00,2020-03-06

In [5]:
df_covid_crime_only

,START_DATE,REPORT_DAT,SHIFT,METHOD,OFFENSE,BLOCK,XBLOCK,YBLOCK,WARD,DISTRICT,LATITUDE,LONGITUDE,END_DATE,date
START_DATE,,,,,,,,,,,,,,
2020-03-07 00:00:18+00:00,2020-03-07 00:00:18+00:00,2020-03-07 23:44:58+00:00,EVENING,OTHERS,THEFT/OTHER,1400 - 1499 BLOCK OF GIRARD STREET NW,397063.060000,139725.800000,1.0,3.0,38.925403,-77.033870,2020-03-07 14:00:22+00:00,2020-03-07
2020-03-07 00:07:26+00:00,2020-03-07 00:07:26+00:00,2020-03-07 03:18:07+00:00,EVENING,OTHERS,THEFT F/AUTO,4300 - 4399 BLOCK OF VARNUM PLACE NE,400322.050000,141492.130000,5.0,4.0,38.941320,-76.996285,2020-03-07 00:47:04+00:00,2020-03-07
2020-03-07 00:17:13+00:00,2020-03-07 00:17:13+00:00,2020-03-07 01:23:10+00:00,EVENING,OTHERS,THEFT/OTHER,3100 - 3299 BLOCK OF 14TH STREET NW,397162.060000,140182.430000,1.0,3.0,38.929517,-77.032730,2020-03-07 00:45:03+00:00,2020-03-07
2020-03-07 00:23:02+00:00,2020-03-07 00:23:02+00:00,2020-03-07 05:16:41+00:00,MIDNIGHT,OTHERS,MOTOR VEHICLE THEFT,4200 - 4207 BLOCK OF GEORGIA AVENUE NW,397783.420000,141577.140000,4.0,4.0,38.942083,-77.025568,2020-03-07 01:23:19+00:00,2020-03-07
2020-03-07 00:30:59+00:00,2020-03-07 00:30:59+00:00,2020-03-07 07:11:23+00:00,MIDNIGHT,OTHERS,THEFT F/AUTO,400 - 499 BLOCK OF V STREET NE,399996.090000,138915.140000,5.0,5.0,38.918105,-77.000045,2020-03-07 06:15:26+00:00,2020-03-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-20 23:40:00+00:00,2021-10-20 23:40:00+00:00,2021-10-21 00:16:07+00:00,EVENING,OTHERS,THEFT/OTHER,1325 - 1399 BLOCK OF PARK ROAD NW,397241.550000,140302.660000,1.0,3.0,38.930600,-77.031814,2021-10-21 00:00:00+00:00,2021-10-20
2021-10-20 23:58:00+00:00,2021-10-20 23:58:00+00:00,2021-10-21 01:40:53+00:00,EVENING,OTHERS,ROBBERY,L STREET NE AND 4TH STREET NE,399950.379998,137318.999997,6.0,5.0,38.903727,-77.000572,NaN,2021-10-20
2021-10-21 02:00:00+00:00,2021-10-21 02:00:00+00:00,2021-10-21 02:50:35+00:00,EVENING,OTHERS,MOTOR VEHICLE THEFT,1200 - 1225 BLOCK OF 28TH STREET NW,395052.940000,137535.080000,2.0,2.0,38.905659,-77.057035,2021-10-21 02:52:00+00:00,2021-10-21
2021-10-21 02:27:00+00:00,2021-10-21 02:27:00+00:00,2021-10-21 03:40:36+00:00,MIDNIGHT,OTHERS,THEFT F/AUTO,2401 - 2499 BLOCK OF 14TH STREET NW,397233.570000,139278.350000,1.0,3.0,38.921373,-77.031901,2021-10-21 02:55:00+00:00,2021-10-21
2021-10-21 03:46:00+00:00,2021-10-21 03:46:00+00:00,2021-10-21 03:58:37+00:00,MIDNIGHT,GUN,ASSAULT W/DANGEROUS WEAPON,200 - 299 BLOCK OF 37TH PLACE SE,404182.407458,135422.580187,7.0,6.0,38.886633,-76.951793,2021-10-21 03:48:00+00:00,2021-10-21

# Adding COVID-cases data

In [7]:
df_covid_cases_data_only = pd.read_csv(os.path.join(data_dir, "Merged", "covid_cases_district-of-columbia-history.csv"))

df_covid_cases_data_only = df_covid_cases_data_only[(df_covid_cases_data_only["state"])=="District of Columbia"]
df_covid_cases_data_only["covid_deaths"] = df_covid_cases_data_only['deaths']
df_covid_cases_data_only['covid_daily_case_count'] = df_covid_cases_data_only['cases']

del df_covid_cases_data_only["state"]
del df_covid_cases_data_only["deaths"]
del df_covid_cases_data_only["cases"]
del df_covid_cases_data_only["fips"]

In [8]:
df_covid_cases_data_only

             date  covid_deaths  covid_daily_case_count
353    2020-03-07             0                       1
387    2020-03-08             0                       1
422    2020-03-09             0                       4
459    2020-03-10             0                       4
500    2020-03-11             0                      10
...           ...           ...                     ...
33783  2021-11-06          1193                   64799
33839  2021-11-07          1193                   64799
33895  2021-11-08          1193                   65050
33951  2021-11-09          1193                   65094
34007  2021-11-10          1193                   65159

[614 rows x 3 columns]

In [9]:
# fix the column types and sort by date

In [10]:
df_covid_cases_data_only['index_date'] = pd.to_datetime(df_covid_cases_data_only['date'])
#df_covid_cases_data['Case_Date'] = df_covid_cases_data_only['date']
df_covid_cases_data_only = df_covid_cases_data_only.set_index(df_covid_cases_data_only['index_date']) #.dt.strftime('%Y-%m-%d')) # should it be END_DATE or what?
df_covid_cases_data_only = df_covid_cases_data_only.sort_index()

df_covid_cases_data_only = df_covid_cases_data_only[['date', 'covid_daily_case_count', 'covid_deaths']]
df_covid_cases_data_only['date'] = pd.to_datetime(df_covid_cases_data_only['date'])
df_covid_cases_data_only = df_covid_cases_data_only.rename(columns={"positive":"covid_daily_case_count"})

# Merging on the following data:

In [11]:
df_covid_cases_data_only.head()

                 date  covid_daily_case_count  covid_deaths
index_date
2020-03-07 2020-03-07                       1             0
2020-03-08 2020-03-08                       1             0
2020-03-09 2020-03-09                       4             0
2020-03-10 2020-03-10                       4             0
2020-03-11 2020-03-11                      10             0

In [12]:
df_covid_crime_only.head(5)

,START_DATE,REPORT_DAT,SHIFT,METHOD,OFFENSE,BLOCK,XBLOCK,YBLOCK,WARD,DISTRICT,LATITUDE,LONGITUDE,END_DATE,date
START_DATE,,,,,,,,,,,,,,
2020-03-07 00:00:18+00:00,2020-03-07 00:00:18+00:00,2020-03-07 23:44:58+00:00,EVENING,OTHERS,THEFT/OTHER,1400 - 1499 BLOCK OF GIRARD STREET NW,397063.06,139725.80,1.0,3.0,38.925403,-77.033870,2020-03-07 14:00:22+00:00,2020-03-07
2020-03-07 00:07:26+00:00,2020-03-07 00:07:26+00:00,2020-03-07 03:18:07+00:00,EVENING,OTHERS,THEFT F/AUTO,4300 - 4399 BLOCK OF VARNUM PLACE NE,400322.05,141492.13,5.0,4.0,38.941320,-76.996285,2020-03-07 00:47:04+00:00,2020-03-07
2020-03-07 00:17:13+00:00,2020-03-07 00:17:13+00:00,2020-03-07 01:23:10+00:00,EVENING,OTHERS,THEFT/OTHER,3100 - 3299 BLOCK OF 14TH STREET NW,397162.06,140182.43,1.0,3.0,38.929517,-77.032730,2020-03-07 00:45:03+00:00,2020-03-07
2020-03-07 00:23:02+00:00,2020-03-07 00:23:02+00:00,2020-03-07 05:16:41+00:00,MIDNIGHT,OTHERS,MOTOR VEHICLE THEFT,4200 - 4207 BLOCK OF GEORGIA AVENUE NW,397783.42,141577.14,4.0,4.0,38.942083,-77.025568,2020-03-07 01:23:19+00:00,2020-03-07
2020-03-07 00:30:59+00:00,2020-03-07 00:30:59+00:00,2020-03-07 07:11:23+00:00,MIDNIGHT,OTHERS,THEFT F/AUTO,400 - 499 BLOCK OF V STREET NE,399996.09,138915.14,5.0,5.0,38.918105,-77.000045,2020-03-07 06:15:26+00:00,2020-03-07

In [13]:
# Merge crime data with covid cases

# df_pre_covid_crime_only
# df_covid_crime_only

In [14]:
df_pre_covid_crime_and_covid_cases = copy.deepcopy(df_pre_covid_crime_only)
df_pre_covid_crime_and_covid_cases['covid_daily_case_count'] = 0
df_pre_covid_crime_and_covid_cases["covid_deaths"] = 0

df_covid_crime_and_cases = pd.merge(df_covid_crime_only, df_covid_cases_data_only, how='inner', on='date')

In [15]:
print("df_pre_covid_crime_only.shape:", df_pre_covid_crime_only.shape)
print("df_covid_crime_only.shape:", df_covid_crime_only.shape)
print()
print("df_pre_covid_crime_and_covid_cases.shape:", df_pre_covid_crime_and_covid_cases.shape)
print("df_covid_crime_and_cases.shape:", df_covid_crime_and_cases.shape)

df_pre_covid_crime_only.shape: (106617, 14)
df_covid_crime_only.shape: (44163, 14)

df_pre_covid_crime_and_covid_cases.shape: (106617, 16)
df_covid_crime_and_cases.shape: (44163, 16)

In [16]:
df_covid_crime_only

,START_DATE,REPORT_DAT,SHIFT,METHOD,OFFENSE,BLOCK,XBLOCK,YBLOCK,WARD,DISTRICT,LATITUDE,LONGITUDE,END_DATE,date
START_DATE,,,,,,,,,,,,,,
2020-03-07 00:00:18+00:00,2020-03-07 00:00:18+00:00,2020-03-07 23:44:58+00:00,EVENING,OTHERS,THEFT/OTHER,1400 - 1499 BLOCK OF GIRARD STREET NW,397063.060000,139725.800000,1.0,3.0,38.925403,-77.033870,2020-03-07 14:00:22+00:00,2020-03-07
2020-03-07 00:07:26+00:00,2020-03-07 00:07:26+00:00,2020-03-07 03:18:07+00:00,EVENING,OTHERS,THEFT F/AUTO,4300 - 4399 BLOCK OF VARNUM PLACE NE,400322.050000,141492.130000,5.0,4.0,38.941320,-76.996285,2020-03-07 00:47:04+00:00,2020-03-07
2020-03-07 00:17:13+00:00,2020-03-07 00:17:13+00:00,2020-03-07 01:23:10+00:00,EVENING,OTHERS,THEFT/OTHER,3100 - 3299 BLOCK OF 14TH STREET NW,397162.060000,140182.430000,1.0,3.0,38.929517,-77.032730,2020-03-07 00:45:03+00:00,2020-03-07
2020-03-07 00:23:02+00:00,2020-03-07 00:23:02+00:00,2020-03-07 05:16:41+00:00,MIDNIGHT,OTHERS,MOTOR VEHICLE THEFT,4200 - 4207 BLOCK OF GEORGIA AVENUE NW,397783.420000,141577.140000,4.0,4.0,38.942083,-77.025568,2020-03-07 01:23:19+00:00,2020-03-07
2020-03-07 00:30:59+00:00,2020-03-07 00:30:59+00:00,2020-03-07 07:11:23+00:00,MIDNIGHT,OTHERS,THEFT F/AUTO,400 - 499 BLOCK OF V STREET NE,399996.090000,138915.140000,5.0,5.0,38.918105,-77.000045,2020-03-07 06:15:26+00:00,2020-03-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-20 23:40:00+00:00,2021-10-20 23:40:00+00:00,2021-10-21 00:16:07+00:00,EVENING,OTHERS,THEFT/OTHER,1325 - 1399 BLOCK OF PARK ROAD NW,397241.550000,140302.660000,1.0,3.0,38.930600,-77.031814,2021-10-21 00:00:00+00:00,2021-10-20
2021-10-20 23:58:00+00:00,2021-10-20 23:58:00+00:00,2021-10-21 01:40:53+00:00,EVENING,OTHERS,ROBBERY,L STREET NE AND 4TH STREET NE,399950.379998,137318.999997,6.0,5.0,38.903727,-77.000572,NaN,2021-10-20
2021-10-21 02:00:00+00:00,2021-10-21 02:00:00+00:00,2021-10-21 02:50:35+00:00,EVENING,OTHERS,MOTOR VEHICLE THEFT,1200 - 1225 BLOCK OF 28TH STREET NW,395052.940000,137535.080000,2.0,2.0,38.905659,-77.057035,2021-10-21 02:52:00+00:00,2021-10-21
2021-10-21 02:27:00+00:00,2021-10-21 02:27:00+00:00,2021-10-21 03:40:36+00:00,MIDNIGHT,OTHERS,THEFT F/AUTO,2401 - 2499 BLOCK OF 14TH STREET NW,397233.570000,139278.350000,1.0,3.0,38.921373,-77.031901,2021-10-21 02:55:00+00:00,2021-10-21
2021-10-21 03:46:00+00:00,2021-10-21 03:46:00+00:00,2021-10-21 03:58:37+00:00,MIDNIGHT,GUN,ASSAULT W/DANGEROUS WEAPON,200 - 299 BLOCK OF 37TH PLACE SE,404182.407458,135422.580187,7.0,6.0,38.886633,-76.951793,2021-10-21 03:48:00+00:00,2021-10-21

In [17]:
df_covid_crime_and_cases

,START_DATE,REPORT_DAT,SHIFT,METHOD,OFFENSE,BLOCK,XBLOCK,YBLOCK,WARD,DISTRICT,LATITUDE,LONGITUDE,END_DATE,date,covid_daily_case_count,covid_deaths
0,2020-03-07 00:00:18+00:00,2020-03-07 23:44:58+00:00,EVENING,OTHERS,THEFT/OTHER,1400 - 1499 BLOCK OF GIRARD STREET NW,397063.060000,139725.800000,1.0,3.0,38.925403,-77.033870,2020-03-07 14:00:22+00:00,2020-03-07,1,0
1,2020-03-07 00:07:26+00:00,2020-03-07 03:18:07+00:00,EVENING,OTHERS,THEFT F/AUTO,4300 - 4399 BLOCK OF VARNUM PLACE NE,400322.050000,141492.130000,5.0,4.0,38.941320,-76.996285,2020-03-07 00:47:04+00:00,2020-03-07,1,0
2,2020-03-07 00:17:13+00:00,2020-03-07 01:23:10+00:00,EVENING,OTHERS,THEFT/OTHER,3100 - 3299 BLOCK OF 14TH STREET NW,397162.060000,140182.430000,1.0,3.0,38.929517,-77.032730,2020-03-07 00:45:03+00:00,2020-03-07,1,0
3,2020-03-07 00:23:02+00:00,2020-03-07 05:16:41+00:00,MIDNIGHT,OTHERS,MOTOR VEHICLE THEFT,4200 - 4207 BLOCK OF GEORGIA AVENUE NW,397783.420000,141577.140000,4.0,4.0,38.942083,-77.025568,2020-03-07 01:23:19+00:00,2020-03-07,1,0
4,2020-03-07 00:30:59+00:00,2020-03-07 07:11:23+00:00,MIDNIGHT,OTHERS,THEFT F/AUTO,400 - 499 BLOCK OF V STREET NE,399996.090000,138915.140000,5.0,5.0,38.918105,-77.000045,2020-03-07 06:15:26+00:00,2020-03-07,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44158,2021-10-20 23:40:00+00:00,2021-10-21 00:16:07+00:00,EVENING,OTHERS,THEFT/OTHER,1325 - 1399 BLOCK OF PARK ROAD NW,397241.550000,140302.660000,1.0,3.0,38.930600,-77.031814,2021-10-21 00:00:00+00:00,2021-10-20,63400,1185
44159,2021-10-20 23:58:00+00:00,2021-10-21 01:40:53+00:00,EVENING,OTHERS,ROBBERY,L STREET NE AND 4TH STREET NE,399950.379998,137318.999997,6.0,5.0,38.903727,-77.000572,NaN,2021-10-20,63400,1185
44160,2021-10-21 02:00:00+00:00,2021-10-21 02:50:35+00:00,EVENING,OTHERS,MOTOR VEHICLE THEFT,1200 - 1225 BLOCK OF 28TH STREET NW,395052.940000,137535.080000,2.0,2.0,38.905659,-77.057035,2021-10-21 02:52:00+00:00,2021-10-21,63474,1186
44161,2021-10-21 02:27:00+00:00,2021-10-21 03:40:36+00:00,MIDNIGHT,OTHERS,THEFT F/AUTO,2401 - 2499 BLOCK OF 14TH STREET NW,397233.570000,139278.350000,1.0,3.0,38.921373,-77.031901,2021-10-21 02:55:00+00:00,2021-10-21,63474,1186
44162,2021-10-21 03:46:00+00:00,2021-10-21 03:58:37+00:00,MIDNIGHT,GUN,ASSAULT W/DANGEROUS WEAPON,200 - 299 BLOCK OF 37TH PLACE SE,404182.407458,135422.580187,7.0,6.0,38.886633,-76.951793,2021-10-21 03:48:00+00:00,2021-10-21,63474,1186

In [18]:
print("df_pre_covid_crime_only.shape:", df_pre_covid_crime_only.shape)
print("df_covid_crime_only.shape:", df_covid_crime_only.shape)
print()
print("df_pre_covid_crime_and_covid_cases.shape:", df_pre_covid_crime_and_covid_cases.shape)
print("df_covid_crime_and_cases.shape:", df_covid_crime_and_cases.shape)

df_pre_covid_crime_only.shape: (106617, 14)
df_covid_crime_only.shape: (44163, 14)

df_pre_covid_crime_and_covid_cases.shape: (106617, 16)
df_covid_crime_and_cases.shape: (44163, 16)

In [19]:
df_pre_covid_crime_and_covid_cases = df_pre_covid_crime_and_covid_cases.dropna()
df_covid_crime_and_cases = df_covid_crime_and_cases.dropna()

In [22]:
df_pre_covid_crime_and_covid_cases.to_csv("pre_covid_crime_and_covid_cases.csv")
df_covid_crime_and_cases.to_csv("covid_crime_and_covid_cases.csv")

# Example for reading in merged dataset that includes Crime and COVID case data

In [ ]:
df_pre_covid_crime_and_covid_cases = pd.read_csv(os.path.join(data_dir, "Merged", "pre_covid_crime_and_covid_cases.csv"))
df_covid_crime_and_cases = pd.read_csv(os.path.join(data_dir, "Merged", "covid_crime_and_cases.csv"))

df_pre_covid_crime_and_covid_cases['REPORT_DAT'] = pd.to_datetime(df_pre_covid_crime_and_covid_cases['REPORT_DAT'])
df_pre_covid_crime_and_covid_cases['START_DATE'] = pd.to_datetime(df_pre_covid_crime_and_covid_cases['START_DATE'])
df_pre_covid_crime_and_covid_cases['END_DATE'] = pd.to_datetime(df_pre_covid_crime_and_covid_cases['END_DATE'])

df_covid_crime_and_cases['REPORT_DAT'] = pd.to_datetime(df_covid_crime_and_cases['REPORT_DAT'])
df_covid_crime_and_cases['START_DATE'] = pd.to_datetime(df_covid_crime_and_cases['START_DATE'])
df_covid_crime_and_cases['END_DATE'] = pd.to_datetime(df_covid_crime_and_cases['END_DATE'])

In [ ]:
df_pre_covid_crime_and_covid_cases = df_pre_covid_crime_and_covid_cases.dropna()
df_covid_crime_and_cases = df_covid_crime_and_cases.dropna()

In [ ]:
print("Pre-COVID Crime with COVID Case data:", df_pre_covid_crime_and_covid_cases.shape)

print("COVID Crime with COVID Case data:", df_covid_crime_and_cases.shape)